# This is a basic workflow to help you get started with Actions

name: Build Debian variant of Polygram Linux

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    

defaults:
  run:
    shell: bash
    working-directory: ./debian

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run:  sudo apt install debootstrap -y; sudo bash build-image.sh
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./debian/polygram-debian.img.tar.gz
          
permissions:
  contents: write
  discussions: write
